detector:
  name: SIFT
matcher:
  id: FLANN
  args:
    - algorithm: 1
      trees: 5
    - check: 50
knn: 2
proportion: 0.7
pass_directory: pass
fail_directory: fail
form_metadata_directory: metadata
